### PR TITLE
Added Hungarian package description

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @mgruner and @carlosfrodriguez 
Here is the Hungarian package description for this module. Please apply this PR before new release.

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @mgruner and @carlosfrodriguez 
Can you merge my translation?

**Comment by urbalazs** [comment]
Hi @mgruner and @carlosfrodriguez
Can you merge my translation? This PR is more than 2 months old. No logic is changed, only Hungarian package description is added.
If you can not merge this PR, can you please tell me, who is the responsible developer for this module?

**Comment by urbalazs** [comment]
I opened a bug report for this PR:
https://bugs.otrs.org/show_bug.cgi?id=12668

**Comment by urbalazs** [comment]
Hi @mgruner and @carlosfrodriguez
Please don't forget to merge my pull request before release the new version! This is the last OTRS module, that has no Hungarian description yet!

**Comment by carlosfrodriguez** [comment]
Hi @urbalazs,

Thank you for your pull request, it was merged in https://github.com/OTRS/OTRSMasterSlave/commit/a650772e7c774b0deaa273641f0841d6ad74272c.

((enjoy))
cr

**Pull request closed without merging**
