### PR TITLE
Update MasterSlave.pm

### PR DESCRIPTION
**Pull request by jensoliver**
Fixes Ticket#2016030142000858

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @jensoliver,

Thank you for your pull request, however this change could not merged in the state it is right now as there are no limitations to include the field in the edit screens in the customer interface that leads into an untested scenario where the screen might break, but also if it does not, it is unwanted that a customer modifies the Master/Slave attributes.

I will recommend you to extend this pull request in order to include a Pre-Action module that works for CustomerTicketMessage and CustomerTicketZoom (follow-up) to disable the field is it comes in the configuration for the screen.

((enjoy))
cr

**Comment by jensoliver** [comment]
Hi Carlos,

as we don't have these test in other areas (like using Prcess Management ID fields in different screens) the possibility should not break the screen. As modifying a Dynamic Field is a seperate value in sysconfig there also should no impact...

**Comment by nilei** [comment]
@carlosfrodriguez, who says it is unwanted that a customer user is modifying the Master/Slave field?

**Comment by carlosfrodriguez** [comment]
Hi @jensoliver,

The package uses an special type of Dynamic Field based on Dropdown, but its values are calculated and not predefined. The way it gets its values is not designed for a Customer user, but for an Agent. At the current state **the field should not be displayed for edit** in the customer screens.

((enjoy))
cr

**Comment by carlosfrodriguez** [comment]
Hi @nilei,

Historically the setting of Master/Slave have been always an agent task, extend this responsibility to the customer might result in unwanted effects for the agents that are working on a set of tickets that has been analyzed and grouped.

For example it might be the case that for handling a issue it is wanted that the state and notes to be forwarded among all slaves, if customers are able to left the ticket from its master or to set in into a wrong master, this will lead to a miss or unwanted information.

For sure we are open to analyze pull requests that implements this new feature (for OTRSMasterSlave 6), they must contain a SysConfig setting to enable it (disabled by default). But at the moment in the current state of the package and for OTRSMasterSlave 5 this behavior is unwanted.

((enjoy))
cr.

**Comment by nilei** [comment]
Hi @carlosfrodriguez, that's fine. I just wanted to mention that we should not generally exclude the customer interface from such features.

:-)
Cheers, Nils

**Pull request closed without merging**
